#!/bin/bash
set -e

# Don't leave an outdated .ssd lying around if the build fails.
rm -f night-world.ssd

# TODO: world-1 contains embedded BASIC and eventually we might want to split it up and
# handle the two parts separately, but let's not worry about that for now. Given the way
# the BASIC code is in the middle of the file, it would be easier to build this from
# component parts neatly once we're no longer concerned with reproducing the original
# binaries exactly.
python world-1.py > src/world-1.asm
# Replace the save line generated by py8dis with our own code. TODO: This is fiddly but
# once world-1.asm stops being generated by py8dis all this will go away anyway.
sed -i '$d' src/world-1.asm
cat >>src/world-1.asm <<-EOF
MAKE_IMAGE =? FALSE
if MAKE_IMAGE
    save "World-1", pydis_start, pydis_end, start
else
    save pydis_start, pydis_end
endif
EOF

mkdir -p tmp
beebasm -v -o tmp/world-1 -i src/world-1.asm > tmp/world-1.lst
cmp orig/world-1 tmp/world-1 || (echo world-1 not rebuilt correctly > /dev/stderr; exit 1)

# TODO: It would probably be possible to use beebasm's PUTBASIC for this, but I have
# hopes of later being able to manually "unpack" world-2.bas and use meaningful variable/
# procedure names and have basictool crunch this at build time.
basictool -t src/world-2.bas tmp/world-2.tok
cmp orig/world-2.tok tmp/world-2.tok || (echo world-2.tok not rebuilt correctly > /dev/stderr; exit 1)

# world-2.asm has been manually modified so world-2.py is now "frozen" as just
# an artefact of the disassembly process.
# python world-2.py > src/world-2.asm
beebasm -v -o tmp/world-2 -i src/world-2.asm > tmp/world-2.lst
cmp orig/world-2 tmp/world-2 || (echo world-2 not rebuilt correctly > /dev/stderr; exit 1)

basictool -t src/nightwo.bas tmp/nightwo.tok
cmp orig/nightwo tmp/nightwo.tok || (echo nightwo.tok not rebuilt correctly > /dev/stderr; exit 1)

beebasm -do tmp/int1.ssd -title "Night World" -opt 3 -i src/disc.asm
beebasm -do tmp/int2.ssd -di tmp/int1.ssd -D MAKE_IMAGE -i src/world-1.asm
beebasm -do night-world.ssd -di tmp/int2.ssd -D MAKE_IMAGE -i src/world-2.asm
